// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dfsmr.proto

/*
Package dfsmr is a generated protocol buffer package.

It is generated from these files:
	dfsmr.proto

It has these top-level messages:
	StartRequest
	AckReply
*/
package dfsmr

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StartRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *StartRequest) Reset()                    { *m = StartRequest{} }
func (m *StartRequest) String() string            { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()               {}
func (*StartRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StartRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AckReply struct {
	Success        bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	SuccessMessage string `protobuf:"bytes,2,opt,name=successMessage" json:"successMessage,omitempty"`
	ErrorMessage   string `protobuf:"bytes,3,opt,name=errorMessage" json:"errorMessage,omitempty"`
}

func (m *AckReply) Reset()                    { *m = AckReply{} }
func (m *AckReply) String() string            { return proto.CompactTextString(m) }
func (*AckReply) ProtoMessage()               {}
func (*AckReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AckReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AckReply) GetSuccessMessage() string {
	if m != nil {
		return m.SuccessMessage
	}
	return ""
}

func (m *AckReply) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*StartRequest)(nil), "StartRequest")
	proto.RegisterType((*AckReply)(nil), "AckReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DistributedFSMRunner service

type DistributedFSMRunnerClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*AckReply, error)
}

type distributedFSMRunnerClient struct {
	cc *grpc.ClientConn
}

func NewDistributedFSMRunnerClient(cc *grpc.ClientConn) DistributedFSMRunnerClient {
	return &distributedFSMRunnerClient{cc}
}

func (c *distributedFSMRunnerClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*AckReply, error) {
	out := new(AckReply)
	err := grpc.Invoke(ctx, "/DistributedFSMRunner/Start", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DistributedFSMRunner service

type DistributedFSMRunnerServer interface {
	Start(context.Context, *StartRequest) (*AckReply, error)
}

func RegisterDistributedFSMRunnerServer(s *grpc.Server, srv DistributedFSMRunnerServer) {
	s.RegisterService(&_DistributedFSMRunner_serviceDesc, srv)
}

func _DistributedFSMRunner_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedFSMRunnerServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DistributedFSMRunner/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedFSMRunnerServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DistributedFSMRunner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DistributedFSMRunner",
	HandlerType: (*DistributedFSMRunnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _DistributedFSMRunner_Start_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dfsmr.proto",
}

func init() { proto.RegisterFile("dfsmr.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x49, 0x2b, 0xce,
	0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x92, 0xe1, 0xe2, 0x09, 0x2e, 0x49, 0x2c, 0x2a,
	0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xe2, 0xe1, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x54, 0xf2, 0xe4, 0xe2, 0x70, 0x4c, 0xce, 0x0e, 0x4a, 0x2d, 0xc8,
	0xa9, 0x14, 0xe2, 0xe7, 0x62, 0x2f, 0x2e, 0x4d, 0x4e, 0x4e, 0x2d, 0x2e, 0x06, 0x4b, 0x72, 0x08,
	0x89, 0x71, 0xf1, 0x41, 0x05, 0x7c, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x25, 0x98, 0x40, 0x9a,
	0x84, 0x44, 0xb8, 0x78, 0x52, 0x8b, 0x8a, 0xf2, 0x8b, 0x60, 0xa2, 0xcc, 0x20, 0x51, 0x23, 0x6b,
	0x2e, 0x11, 0x97, 0xcc, 0xe2, 0x92, 0xa2, 0xcc, 0xa4, 0xd2, 0x92, 0xd4, 0x14, 0xb7, 0x60, 0xdf,
	0xa0, 0xd2, 0xbc, 0xbc, 0xd4, 0x22, 0x21, 0x65, 0x2e, 0x56, 0xb0, 0x03, 0x84, 0x78, 0xf5, 0x90,
	0x1d, 0x22, 0xc5, 0xa9, 0x07, 0xb3, 0x59, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x58, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x98, 0x4f, 0x5a, 0x28, 0xbb, 0x00, 0x00, 0x00,
}
